services:
  drawio-export:
    image: rlespinasse/drawio-export
    volumes:
      - .:/data
    command: --format png --output /data/.export /data/resources

  latex:
    image: texlive/texlive
    volumes:
      - .:/data
    working_dir: /data
    command: pdflatex -output-directory /data/.export report.tex
    depends_on:
      drawio-export:
        condition: service_completed_successfully
