version: '3.8'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      # allow for making requests from HMI via browser
      - "5000:5000"
    volumes:
      - ./backend/src:/app
    environment:
      - OPC_UA_URL=opc.tcp://172.28.44.48:4840
      - OPC_UA_URL_FALLBACK=opc.tcp://192.168.0.1:4840
      - DB_URL=${DB_URL}
      - DB_TOKEN=${DB_TOKEN}
      - DB_ORG=${DB_ORG}
      - DB_BUCKET_ROBOT=${DB_BUCKET_ROBOT}

  database:
    image: influxdb:2.8.0
    ports:
      - "8086:8086"
    volumes:
      - database_data:/var/lib/influxdb2
      - ./db/influxdb-init:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dummy-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=dummy-pswd-1234
      - DOCKER_INFLUXDB_INIT_ORG=${DB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DB_BUCKET_INIT}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DB_TOKEN}
      - BUCKET_ROBOT=${DB_BUCKET_ROBOT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 5s
      timeout: 2s
      retries: 10

  hmi:
    build:
      context: ./hmi
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=dummy-user
      - GF_SECURITY_ADMIN_PASSWORD=dummy-pswd-1234
      - DB_URL=${DB_URL}
      - DB_TOKEN=${DB_TOKEN}
      - DB_ORG=${DB_ORG}
      - DB_BUCKET_INIT=${DB_BUCKET_INIT}

    # substitute environment variables into datasources
    entrypoint: >
      /bin/sh -c "envsubst < /etc/grafana/provisioning/datasources/datasource.yml.template > /etc/grafana/provisioning/datasources/datasource.yml && /run.sh"
    volumes:
      - ./hmi/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./hmi/grafana/provisioning:/etc/grafana/provisioning
      - ./hmi/grafana/dashboards:/var/lib/grafana/dashboards
      # TODO: remove
      - hmi_data:/var/lib/grafana

    restart: unless-stopped

volumes:
  database_data:
  hmi_data:
