version: '3.8'

services:
  nodered:
    build:
      context: ./nodered
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    restart: unless-stopped

  influxdb:
    image: influxdb:3.8.3-core
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_DB=robot
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.0.0-23336907879-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  nodered_data:
  influxdb_data:
  grafana_data:
