{
 "title": "Robot",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Target high-level motion",
   "type": "timeseries",
   "description": "High-level target velocities, regardless of individual wheels",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"robot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"motion_intent\")\r\n  |> filter(fn: (r) => r._field == \"v\" or r._field == \"omega\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "Control mode",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"robot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"wheel_state\")\r\n  |> filter(fn: (r) => r._field == \"pwm_override_enable\")\r\n  |> filter(fn: (r) => r.wheel_side == \"left\")\r\n  |> map(fn: (r) => ({\r\n      r with _value: if r._value then 0 else 1\r\n  }))"
    }
   ]
  },
  {
   "title": "Motion control",
   "type": "volkovlabs-form-panel",
   "description": "Commands sent to the backend to apply the desired velocities",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"robot\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"motion_intent\")\r\n  |> filter(fn: (r) => r._field == \"omega\" or r._field == \"v\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Override PWM",
   "type": "volkovlabs-form-panel",
   "description": "Manual motor control (0 = full reverse, 1 = full forward)",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"robot\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"wheel_state\")\r\n  |> filter(fn: (r) => r._field == \"pwm_override\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with _value: math.round(x: r._value * 100.0) / 100.0\r\n  }))"
    }
   ]
  },
  {
   "title": "Rotation speed",
   "type": "timeseries",
   "description": "Rotation speed of individual speeds",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"robot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"wheel_state\")\r\n  |> filter(fn: (r) => r._field == \"actual_speed\" or r._field == \"target_speed\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "PWM",
   "type": "timeseries",
   "description": "PWM signal to control wheel rotation",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"robot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"wheel_state\")\r\n  |> filter(fn: (r) => r._field == \"pwm\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "Motor temperature",
   "type": "timeseries",
   "description": "Temperature of motors",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"robot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"wheel_state\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "Rotation speed error",
   "type": "timeseries",
   "description": "Error between target and actual rotation speed",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"robot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"wheel_state\")\r\n  |> filter(fn: (r) => r._field == \"actual_speed\" or r._field == \"target_speed\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> pivot(\r\n      rowKey: [\"_time\"],\r\n      columnKey: [\"_field\", \"wheel_side\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      left_error: r.target_speed_left - r.actual_speed_left,\r\n      right_error: r.target_speed_right - r.actual_speed_right\r\n  }))"
    }
   ]
  },
  {
   "title": "Wheel position",
   "type": "timeseries",
   "description": "Wheel position",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"robot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"wheel_state\")\r\n  |> filter(fn: (r) => r._field == \"actual_angle\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)"
    }
   ]
  }
 ]
}